services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload
