version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - db_data:/app/data 
    env_file:
      - .env
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  seeder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seeder
    volumes:
      - ./app:/app/app 
      - db_data:/app/data 
    env_file:
      - .env
    command: python -m app.seeder

volumes:
  db_data: